#!/usr/bin/env python3
"""Generate compact Bastion Loot metadata from the official 1.16.5 jar."""

import argparse
import hashlib
import json
import zipfile
from pathlib import Path

from generate_loot_tables_1_16_1 import integer_range, parse_entry, joined_flags


OFFICIAL_CLIENT_SHA1 = "37fd3c903861eeff3bc24b71eed48f828b5269c8"
TABLES = [
    "bastion_bridge",
    "bastion_hoglin_stable",
    "bastion_other",
    "bastion_treasure",
]


def sha1_file(path):
    digest = hashlib.sha1()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_tables(jar):
    digest = sha1_file(jar)
    if digest != OFFICIAL_CLIENT_SHA1:
        raise ValueError(
            f"Expected official 1.16.5 client SHA-1 {OFFICIAL_CLIENT_SHA1}, "
            f"received {digest}"
        )
    parsed = []
    with zipfile.ZipFile(str(jar), "r") as archive:
        for name in TABLES:
            entry_name = (
                "data/minecraft/loot_tables/chests/" + name + ".json"
            )
            data = json.loads(archive.read(entry_name))
            pools = []
            for pool_index, pool in enumerate(data.get("pools", [])):
                context = f"{entry_name} pool {pool_index}"
                low, high = integer_range(pool["rolls"], context + " rolls")
                entries = [
                    parse_entry(entry, f"{context} entry {entry_index}")
                    for entry_index, entry in enumerate(pool["entries"])
                ]
                pools.append({"min": low, "max": high, "entries": entries})
            parsed.append({"name": name, "pools": pools})
    return parsed, digest


def render(tables, digest):
    entries = []
    pools = []
    definitions = []
    for table in tables:
        first_pool = len(pools)
        for pool in table["pools"]:
            first_entry = len(entries)
            entries.extend(pool["entries"])
            pools.append({
                "min": pool["min"],
                "max": pool["max"],
                "first": first_entry,
                "count": len(pool["entries"]),
            })
        definitions.append((first_pool, len(table["pools"])))

    lines = [
        "/* Generated by tools/generate_bastion_loot_tables_1_16_5.py.",
        f" * Official 1.16.5 client jar SHA-1: {digest}",
        " * Contains compact Loot metadata only; no raw JSON is embedded.",
        " */",
        "",
        "static const LootTableEntry16 BASTION_LOOT_ENTRIES_1_16_5[] = {",
    ]
    for entry in entries:
        lines.append(
            "    {%s, %d, %d, %d, %s},"
            % (entry["item"], entry["weight"], entry["min"],
               entry["max"], joined_flags(entry["flags"]))
        )
    lines += [
        "};", "",
        "static const LootTablePool16 BASTION_LOOT_POOLS_1_16_5[] = {",
    ]
    for pool in pools:
        lines.append(
            "    {%d, %d, %d, %d},"
            % (pool["min"], pool["max"], pool["first"], pool["count"])
        )
    lines += [
        "};", "",
        "static const LootTableDefinition16 BASTION_LOOT_TABLES_1_16_5[] = {",
    ]
    for first, count in definitions:
        lines.append(f"    {{{first}, {count}}},")
    lines += [
        "};", "",
        "static const char *const BASTION_LOOT_TABLE_NAMES_1_16_5[] = {",
    ]
    for table in tables:
        lines.append(f'    "{table["name"]}",')
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--jar", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    tables, digest = read_tables(args.jar)
    args.output.write_text(render(tables, digest), encoding="utf-8")


if __name__ == "__main__":
    main()
